# Generated by Django 5.2.4 on 2025-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
