# Generated by Django 5.2.4 on 2025-12-11 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_amount_paid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add product specs like Word/Doc style', null=True),
        ),
    ]
