# Generated by Django 5.2.4 on 2025-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('partial_paid', 'Partially Paid'), ('paid', 'Fully Paid'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='order_placed', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
