# Generated by Django 5.2.4 on 2025-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_order_status_order_payment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('preparing', 'Preparing'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Order Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed'), ('on_hold', 'On Hold')], default='order_placed', max_length=30),
        ),
    ]
