# Generated by Django 5.2.4 on 2026-01-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
