# Generated by Django 5.2.4 on 2026-01-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_order_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
