# Generated by Django 5.2.4 on 2026-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_1', models.ImageField(upload_to='home_slider/')),
                ('slider_2', models.ImageField(upload_to='home_slider/')),
                ('slider_3', models.ImageField(upload_to='home_slider/')),
                ('right_image_1', models.ImageField(upload_to='home_slider/')),
                ('right_image_2', models.ImageField(upload_to='home_slider/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
